### ISSUE TITLE
Converted files are not saved sometimes

### ISSUE THREAD

**Issue by uguratar** [xthiago/pdf-version-converter#1]
Hi,
When copying the converted file via Symfony FS, [here](https://github.com/xthiago/pdf-version-converter/blob/master/src/Converter/GhostscriptConverter.php#L73) sometimes the new file is not overwritten.

I think this is the default behavior for copy function, It is described here.
https://github.com/symfony/filesystem/blob/master/Filesystem.php#L27
Just wanted to let you know. 

Thank you for the useful library.

**Comment by xthiago** [comment]
Nice catch! I will fix it. 
Thank you!
