### ISSUE TITLE
Error during composer install

### ISSUE THREAD

**Issue by Thavia** [xthiago/pdf-version-converter#12]
composer require xthiago/pdf-version-converter dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing xthiago/pdf-version-converter (dev-master 10bfb95): Cloning 10bfb95366
    10bfb95366359925025501fea662d4cf4e3735f0 is gone (history was rewritten?)
    Failed to download xthiago/pdf-version-converter from source: Failed to execute git checkout '10bfb95366359925025501fea662d4cf4e3735f0' -- && git reset --hard '10bfb95366359925025501fea662d4cf4e3735f0' --

Note: checking out '10bfb95366359925025501fea662d4cf4e3735f0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 10bfb95... Merge pull request #10 from edegaudenzi/master
error: unable to create file tests/files/repo/v1.7 filename with "Sp3ci4l"; <'Ch4r5'> !£$%&()=?^[]{}è@#§.pdf (Protocol error)
fatal: Could not reset index file to revision '10bfb95366359925025501fea662d4cf4e3735f0'.

    Now trying to download from dist
  - Installing xthiago/pdf-version-converter (dev-master 10bfb95): Downloading (100%)
Installation failed, reverting ./composer.json to its original content.

**Comment by xthiago** [comment]
This issue seems the same as reported on #11.

**Comment by xthiago** [comment]
@Thavia, could you try to install the library again as I mentioned in https://github.com/xthiago/pdf-version-converter/issues/11#issuecomment-296454207 ?
