### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bilal07** [xthiago/pdf-version-converter#17]
Hello thiago,

**after I run the command (composer install), I do not have the folder "Xthiago \ PDFVersionConverter"
so I created an index.php file:**

`<?php
// import the namespaces
use Xthiago\PDFVersionConverter\Guesser\RegexGuesser;
// [..]

$guesser = new RegexGuesser();
echo $guesser->guess('/path/to/my/file.pdf'); // will print something like '1.4'`

**I have the following error**:

Fatal error: Class 'Xthiago \ PDFVersionConverter \ Guesser \ RegexGuesser' not found in C: \ wamp \ www \ pdf-version-converter-1.0.5 \ index.php on line 6

**thank you  for your help**

**Comment by xthiago** [comment]
Hi @bilal07,

I guess you forget to import the composer autoloader in your script.

You can do:

```php
<?php

// You need to import the composer autoloader like that:
require __DIR__.'/vendor/autoload.php'; // <---

// import the namespaces
use Xthiago\PDFVersionConverter\Guesser\RegexGuesser;
// [..]

$guesser = new RegexGuesser();
echo $guesser->guess('/path/to/my/file.pdf'); // will print something like '1.4'
```
